---
version: "2.0"
services:
  web:
    image: mysticlabss/multisig:v0.1.1
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - PUBLIC_DENO_SERVERLESS_URL=https://api.mysticlabs.xyz
      - PUBLIC_SNAP_VERSION=0.1.22
      - PUBLIC_APPWRITE_URL=your-appwrite-url
      - PUBLIC_APPWRITE_FUNCTION_PROJECT_ID=your-project-id
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000
deployment:
  web:
    dcloud:
      profile: web
      count: 1
